spring:
  datasource:
#    url: "jdbc:mysql://localhost:3306/mymagazine"
    url: "jdbc:mysql://springboot-db.coahhlorbmh0.ap-northeast-2.rds.amazonaws.com:3306/myblog"
    username: simononze
    password: fqvi7469!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: jwtsecret

logging.level:
  org.hibernate.SQL: debug